const GET_INTERESTS_SUCCESS = "GET_INTERESTS_SUCCESS"
const SELECT_INTEREST = "SELECT_INTEREST"
const SAVE_MY_INTERESTS = "SAVE_MY_INTERESTS"

export default {
	GET_INTERESTS_SUCCESS,
	SELECT_INTEREST,
	SAVE_MY_INTERESTS
}
