const LOCATION_UPDATED = "LOCATION_UPDATED"
const ADDRESS_UPDATED = "ADDRESS_UPDATED"
const FOUND_MATCH = "FOUND_MATCH"
const UPDATE_NAVIGATION_DURATION = "UPDATE_NAVIGATION_DURATION"

export default {
	LOCATION_UPDATED,
	ADDRESS_UPDATED,
	FOUND_MATCH,
	UPDATE_NAVIGATION_DURATION
}
