const LOGOUT = "LOGOUT"
const TOGGLE_IN_APP_SOUNDS = "TOGGLE_IN_APP_SOUNDS"
const TOGGLE_MESSAGE_LIKES = "TOGGLE_MESSAGE_LIKES"

export default {
	LOGOUT,
	TOGGLE_IN_APP_SOUNDS,
	TOGGLE_MESSAGE_LIKES
}
