const AUTH_FACEBOOK_SUCCESS = "AUTH_FACEBOOK_SUCCESS"
const AUTH_FACEBOOK_FAIL = "AUTH_FACEBOOK_FAIL"
const LOGOUT_FACEBOOK_SUCCESS = "LOGOUT_FACEBOOK_SUCCESS"
const GET_MY_INTERESTS_SUCCESS = "GET_MY_INTERESTS_SUCCESS"

export default {
	AUTH_FACEBOOK_SUCCESS,
	AUTH_FACEBOOK_FAIL,
	LOGOUT_FACEBOOK_SUCCESS,
	GET_MY_INTERESTS_SUCCESS
}
